services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        expose:
            - "9000"
        volumes:
            - ./:/var/www
        depends_on:
            - postgres

    postgres:
        image: postgres:16
        container_name: laravel-postgres
        restart: always
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8081:8081"
        volumes:
            - ./:/var/www
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/app.conf
        depends_on:
            - app

volumes:
    postgres-data:
